### ISSUE TITLE
Issues on command regarding to folder path

### ISSUE THREAD

**Issue by Liu233w** [TNG/please-cli#20]
There are issues when I am trying to use following command:
```
❯ pl open the folder in intellij idea
💡 Command:
  I'm sorry, but as an AI language model, I don't have access to your local files. However, the command to open a folder in IntelliJ IDEA would be: `idea /path/to/folder` (replace `/path/to/folder` with the actual path to the folder).
```
If I change the wording to `current folder`, the result is like:
```
❯ pl open current folder in intellij idea
💡 Command:
  I do not know.
```
Expected result:
```
idea .
```

Context:
alias pl="please -l"

**Comment by thomas-endres-tng** [comment]
Hi Shumin ... unfortunately not all commands will work. Please be aware that please does not know your folder structure and that we cannot change the way GPT4 is working internally here. Although the command seems logical to us, it might not be for the language model. You might tweak the prompts a bit, but every extra token will cost extra money for EVERY command. :-(

**Comment by Liu233w** [comment]
I tried to tweak the prompt a bit so it can refer current directory as `.` or `$PWD` but did not succeed. Maybe it just does not have enough data for intellij idea or GPT3.5 is not smart enough :joy:

**Comment by thomas-endres-tng** [comment]
Have you tried with the proxy and GPT4?

**Comment by thomas-endres-tng** [comment]
Seems to work with GPT-4.

`please open IntelliJ in the local folder
💡 Command:
  intellij-idea-community .

❗ What should I do? [use arrow keys to navigate]
  [I] Invoke   [C] Copy to clipboard   [A] Abort`

**Comment by Liu233w** [comment]
Thanks for experimenting. In some outputs it can also output something like `intellij-idea .` in GPT3, although the correct command is `idea .`
I also tried the prompt like `open the folder in vscode` and it worked. So probably it is because the lack of data.
