### ISSUE TITLE
Get an Error The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by apenev** [TNG/please-cli#22]
When I try the command:
 % please tell me the current time in Munich

I recieve the following error:

Error: Received HTTP status 404
The model: `gpt-4` does not exist
alexanderpenev@Alexanders-MacBook-Pro-m1 rbppm % 

I have a paid account so I could choose between 
Can I somehow switchback to 3.5 per config? 
Thanks in advance and best regards,
Alex

**Comment by thomas-endres-tng** [comment]
This happens if for your key GPT4 is not unlocked. You need to apply for GPT4 API access to get it. You can use the -l version (for GPT3.5) which should work for every API key.

**Comment by apenev** [comment]
ah yes, with -l it works, do you know by chance how I apply for 4.0? I thought the account on chatgpt and openai api is the same but seems not to be 

Thanks for the support

**Comment by thomas-endres-tng** [comment]
https://openai.com/waitlist/gpt-4-api

**Comment by apenev** [comment]
thanks a lot
