### ISSUE TITLE
Feature request - invoke leaves the command in shell history 

### ISSUE THREAD

**Issue by crushingCodes** [TNG/please-cli#32]
I am enjoying this tool since starting to use it. I noticed one thing that would be handy is if you could save the command that is invoked to shell history. I often start a command with something like `docker` and then use the up and down keys to browse through previous commands. Currently you just get the `please ...` command saved, but not the invoked command. Wondering if this is something that would get accepted if I created a pull request.

**Comment by thomas-endres-tng** [comment]
Please have a look at https://github.com/TNG/please-cli/pull/34
